name: data_viz_workshop
channels:
    - conda-forge
dependencies: 
    - python=3.10
    - bokeh=2.4.3
    - ffmpeg=5.1.2
    - geopandas=0.12.1
    - jupyterlab=3.5.2
    - matplotlib=3.6.2
    - numpy=1.23.5
    - pandas=1.5.2
    - seaborn=0.11.2
    - shapely=1.8.5
    - pyviz::geoviews-core=1.9.5
    - pyviz::geoviews=1.9.5
    - pyviz::holoviews=1.15.3
    - pyviz::hvplot=0.8.2
    - pyviz::panel=0.14.2
